INSERT INTO program
VALUES(null, CURRENT_TIMESTAMP, 60, 'my Program',  CURRENT_TIMESTAMP),
  (null, CURRENT_TIMESTAMP, 120, 'Other Program', CURRENT_TIMESTAMP),
  (null, CURRENT_TIMESTAMP, 15, 'Third Program', CURRENT_TIMESTAMP);


INSERT INTO activity
VALUES(NULL, 15, 'Pushups', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
  (NULL, 30, 'Situps', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
  (NULL, 60, 'Jumping Jacks',CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP, 2);

SELECT * FROM program;


SELECT * FROM activity;