INSERT INTO program
VALUES('1', CURRENT_TIMESTAMP, 60, 'my Program',  CURRENT_TIMESTAMP),
  ('2', CURRENT_TIMESTAMP, 120, 'Other Program', CURRENT_TIMESTAMP),
  ('3', CURRENT_TIMESTAMP, 15, 'Third Program', CURRENT_TIMESTAMP);


SELECT * FROM program;